Version: 1.8 # minimal SMASH version to use with this config file

Logging:
  default: INFO

General:
  Modus: Collider
  Time_Step_Mode: Fixed
  Delta_Time: 0.01
  End_Time: 15.
  Randomseed: -1
  Nevents: 3

Lattice:
  Origin: [-24.5, -24.5, -24.5]
  Sizes: [49.0, 49.0, 49.0]
  Cell_Number: [49, 49, 49]
  Periodic: False
  Potentials_Affect_Thresholds: False

Output:
  Output_Interval: 0.1
  Thermodynamics:
    Only_Participants: True
    Format: [Lattice_Binary]
    Type: hadron
    Quantities: [rho_eckart, tmn_landau, landau_velocity, j_QBS]

Modi:
  Collider:
    Projectile:
      Particles: {2212: 79, 2112: 118}
    Target:
      Particles: {2212: 79, 2112: 118}
    E_Kin: 80.
    Fermi_Motion: frozen
    Impact:
      Value: 6.
